services:
  - type: web
    name: CampusEventManagement
    env: node
    packageManager: npm
    nodeVersion: 14.x
    buildCommand: "cd client && npm install --legacy-peer-deps && npm run build"
    startCommand: "npm start"
